# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random as rn

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1280, 720)
        MainWindow.setStyleSheet("QStackedWidget#stackedWidget{\n"
"background-image: url(:/BGHD/BgHD.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1281, 721))
        self.stackedWidget.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_menu = QtWidgets.QWidget()
        self.main_menu.setObjectName("main_menu")
        self.label_3 = QtWidgets.QLabel(self.main_menu)
        self.label_3.setGeometry(QtCore.QRect(410, 90, 471, 201))
        self.label_3.setStyleSheet("image: url(:/Logo/Logo.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.main_menu)
        self.label_4.setGeometry(QtCore.QRect(500, 640, 311, 21))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.startBtn = QtWidgets.QPushButton(self.main_menu, clicked=lambda :self.startBtnClick())
        self.startBtn.setGeometry(QtCore.QRect(520, 390, 251, 91))
        self.startBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startBtn.setStyleSheet("image: url(:/startBtn/Start.png);")
        self.startBtn.setText("")
        self.startBtn.setObjectName("startBtn")
        self.quitBtn = QtWidgets.QPushButton(self.main_menu, clicked=lambda :exit())
        self.quitBtn.setGeometry(QtCore.QRect(520, 500, 251, 91))
        self.quitBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.quitBtn.setStyleSheet("\n"
"image: url(:/quitbtn/Quit.png);")
        self.quitBtn.setText("")
        self.quitBtn.setObjectName("quitBtn")
        self.stackedWidget.addWidget(self.main_menu)
        self.game = QtWidgets.QWidget()
        self.game.setObjectName("game")
        self.label_8 = QtWidgets.QLabel(self.game)
        self.label_8.setGeometry(QtCore.QRect(500, 640, 311, 21))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.paperBtn = QtWidgets.QPushButton(self.game, clicked=lambda :self.gameStart(self.paperBtn))
        self.paperBtn.setGeometry(QtCore.QRect(1050, 500, 151, 131))
        self.paperBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.paperBtn.setStyleSheet("border-radius: 20px;\n"
"image: url(:/circles/paper.png);")
        self.paperBtn.setText("")
        self.paperBtn.setObjectName("paperBtn")
        self.mainMenuLb = QtWidgets.QPushButton(self.game, clicked=lambda :self.mainMenuBtnClick())
        self.mainMenuLb.setGeometry(QtCore.QRect(80, 560, 251, 81))
        self.mainMenuLb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mainMenuLb.setStyleSheet("border-radius: 20px;\n"
"image: url(:/mmenu/Mmenu.png);")
        self.mainMenuLb.setText("")
        self.mainMenuLb.setObjectName("mainMenuLb")
        self.rockBtn = QtWidgets.QPushButton(self.game, clicked=lambda :self.gameStart(self.rockBtn))
        self.rockBtn.setGeometry(QtCore.QRect(730, 500, 151, 131))
        self.rockBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rockBtn.setStyleSheet("border-radius: 20px;\n"
"image: url(:/circles/rockFinal.png);")
        self.rockBtn.setText("")
        self.rockBtn.setObjectName("rockBtn")
        self.ComputerLb = QtWidgets.QLabel(self.game)
        self.ComputerLb.setGeometry(QtCore.QRect(40, 100, 421, 311))
        self.ComputerLb.setStyleSheet("\n"
"image: url(:/circles/questionMark.png);")
        self.ComputerLb.setText("")
        self.ComputerLb.setObjectName("ComputerLb")
        self.CenterLb = QtWidgets.QFrame(self.game)
        self.CenterLb.setGeometry(QtCore.QRect(490, 230, 301, 131))
        self.CenterLb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CenterLb.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CenterLb.setObjectName("CenterLb")
        self.PlayerLb = QtWidgets.QLabel(self.game)
        self.PlayerLb.setGeometry(QtCore.QRect(810, 100, 421, 311))
        self.PlayerLb.setStyleSheet("image: url(:/circles/questionMark.png);")
        self.PlayerLb.setText("")
        self.PlayerLb.setObjectName("PlayerLb")
        self.RezultatLb = QtWidgets.QLabel(self.game)
        self.RezultatLb.setGeometry(QtCore.QRect(440, 130, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RezultatLb.setFont(font)
        self.RezultatLb.setStyleSheet("color: rgb(255, 255, 255);")
        self.RezultatLb.setText("")
        self.RezultatLb.setObjectName("RezultatLb")
        self.scrissorsBtn = QtWidgets.QPushButton(self.game, clicked=lambda :self.gameStart(self.scrissorsBtn))
        self.scrissorsBtn.setGeometry(QtCore.QRect(890, 500, 151, 131))
        self.scrissorsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scrissorsBtn.setStyleSheet("border-radius: 20px;\n"
"image: url(:/circles/scrissors.png);")
        self.scrissorsBtn.setText("")
        self.scrissorsBtn.setObjectName("scrissorsBtn")
        self.RezultatLb_2 = QtWidgets.QLabel(self.game)
        self.RezultatLb_2.setGeometry(QtCore.QRect(160, 50, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RezultatLb_2.setFont(font)
        self.RezultatLb_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.RezultatLb_2.setObjectName("RezultatLb_2")
        self.RezultatLb_3 = QtWidgets.QLabel(self.game)
        self.RezultatLb_3.setGeometry(QtCore.QRect(950, 50, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RezultatLb_3.setFont(font)
        self.RezultatLb_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.RezultatLb_3.setObjectName("RezultatLb_3")
        self.stackedWidget.addWidget(self.game)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def gameStart(self, btn):

        # self.ComputerLb.setStyleSheet("image: url(:/circles/questionMark.png);")
        # self.PlayerLb.setStyleSheet("image: url(:/circles/questionMark.png);")

        # Schimbam imaginea care corespunde cu butonul apasat
        stylestr = btn.styleSheet()
        self.PlayerLb.setStyleSheet(stylestr)

        # Stabilim ce a ales jucatorul

        playerChoise = 0
        if btn == self.rockBtn:
            playerChoise = 1
        elif btn == self.scrissorsBtn:
            playerChoise = 2
        elif btn == self.paperBtn:
            playerChoise = 3

        chiose_name = ""
        if playerChoise == 1:
            choice_name = 'Piatra'
        elif playerChoise == 2:
            choice_name = 'Foarfece'
        else:
            choice_name = 'Hartie'


        compChoise = rn.randint(1, 3)

        if compChoise == 1:
            self.ComputerLb.setStyleSheet("image: url(:/circles/rockFinal.png);")
        elif compChoise == 2:
            self.ComputerLb.setStyleSheet("image: url(:/circles/scrissors.png);")
        elif compChoise == 3:
            self.ComputerLb.setStyleSheet("image: url(:/circles/paper.png);")

        if compChoise == 1:
            comp_chiose_name = 'Piatra'
        elif compChoise == 2:
            comp_chiose_name = 'Foarfece'
        else:
            comp_chiose_name =  'Hartie'

        self.RezultatLb.setText("")

        if playerChoise == compChoise:
            self.RezultatLb.setText("Egalitate")
            result = "Egalitate"
        elif ((playerChoise == 1 and compChoise == 2) or
            (playerChoise == 2 and compChoise == 1)):
            self.RezultatLb.setText("Piatra a cstiaga")
            result = "Piatra"

        elif ((playerChoise == 1 and compChoise == 3) or
              (playerChoise == 3 and compChoise == 1)):
            self.RezultatLb.setText("Hartia a cstiaga")
            result = "Foarfece"
        elif ((playerChoise == 2 and compChoise == 3) or
              (playerChoise == 3 and compChoise == 2)):
            self.RezultatLb.setText("Foarfecele au castiaga")
            result = "Foarfece"

            # #Se printeaza castigatorul
            # if result == 'Egalitate':
            #     self.RezultatLb.setText(result)
            # elif result == choice_name:
            #     self.RezultatLb.setText("A castigat utilizatorul")
            # else:
            #     self.RezultatLb.setText("A castigat calculatorul")

    def startBtnClick(self):
        self.stackedWidget.setCurrentWidget(self.game)

    def mainMenuBtnClick(self):
        self.stackedWidget.setCurrentWidget(self.main_menu)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Plesca Virgiliu Copyright © 2021. All rights reserved."))
        self.label_8.setText(_translate("MainWindow", "Plesca Virgiliu Copyright © 2021. All rights reserved."))
        self.RezultatLb_2.setText(_translate("MainWindow", "Calculatorul"))
        self.RezultatLb_3.setText(_translate("MainWindow", "Jucatorul"))
import BGHD_rc
import Logo_rc
import Start_rc
import mmenu_rc
import quit_rc
import rock_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
