# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_menu_last.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1280, 720)
        MainWindow.setStyleSheet("QWidget#centralwidget\n"
"{\n"
"    background-image: url(:/BGHD/BgHD.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ComputerLb = QtWidgets.QLabel(self.centralwidget)
        self.ComputerLb.setGeometry(QtCore.QRect(40, 100, 421, 311))
        self.ComputerLb.setStyleSheet("image: url(:/Rock/questionMark.png);")
        self.ComputerLb.setText("")
        self.ComputerLb.setObjectName("ComputerLb")
        self.PlayerLb = QtWidgets.QLabel(self.centralwidget)
        self.PlayerLb.setGeometry(QtCore.QRect(810, 100, 421, 311))
        self.PlayerLb.setStyleSheet("image: url(:/Rock/questionMark.png);")
        self.PlayerLb.setText("")
        self.PlayerLb.setObjectName("PlayerLb")
        self.RezultatLb = QtWidgets.QLabel(self.centralwidget)
        self.RezultatLb.setGeometry(QtCore.QRect(440, 120, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RezultatLb.setFont(font)
        self.RezultatLb.setStyleSheet("color: rgb(255, 255, 255);")
        self.RezultatLb.setText("")
        self.RezultatLb.setObjectName("RezultatLb")
        self.CenterLb = QtWidgets.QFrame(self.centralwidget)
        self.CenterLb.setGeometry(QtCore.QRect(490, 220, 301, 131))
        self.CenterLb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CenterLb.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CenterLb.setObjectName("CenterLb")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(500, 650, 311, 21))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.mainMenuBtn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.dostuff())
        self.mainMenuBtn.setGeometry(QtCore.QRect(80, 560, 251, 81))
        self.mainMenuBtn.setStyleSheet("border-radius: 20px;\n"
"image: url(:/mmenu/Mmenu.png);")
        self.mainMenuBtn.setText("")
        self.mainMenuBtn.setObjectName("mainMenuBtn")
        self.scrissorsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.scrissorsBtn.setGeometry(QtCore.QRect(890, 510, 151, 131))
        self.scrissorsBtn.setStyleSheet("border-radius: 20px;\n"
"image: url(:/Rock/scrissors.png);")
        self.scrissorsBtn.setText("")
        self.scrissorsBtn.setObjectName("scrissorsBtn")
        self.paperBtn = QtWidgets.QPushButton(self.centralwidget)
        self.paperBtn.setGeometry(QtCore.QRect(1050, 510, 151, 131))
        self.paperBtn.setStyleSheet("border-radius: 20px;\n"
"image: url(:/Rock/paper.png);")
        self.paperBtn.setText("")
        self.paperBtn.setObjectName("paperBtn")
        self.rockBtn = QtWidgets.QPushButton(self.centralwidget)
        self.rockBtn.setGeometry(QtCore.QRect(730, 510, 151, 131))
        self.rockBtn.setStyleSheet("border-radius: 20px;\n"
"image: url(:/Rock/rockFinal.png);")
        self.rockBtn.setText("")
        self.rockBtn.setObjectName("rockBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def dostuff(self):
        self.RezultatLb.setText("Clicked yeeey!!!")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Plesca Virgiliu Copyright © 2021. All rights reserved."))
import BGHD_rc
import GameButtons_rc
import Logo_rc
import Start_rc
import mmenu_rc
import quit_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
