# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu_last.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1280, 720)
        MainWindow.setStyleSheet("QWidget#centralwidget\n"
"{\n"
"    background-image: url(:/BGHD/BgHD.png);\n"
"}")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.QuitLb = QtWidgets.QLabel(self.centralwidget)
        self.QuitLb.setGeometry(QtCore.QRect(500, 500, 251, 81))
        self.QuitLb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QuitLb.setStyleSheet("image: url(:/quitbtn/Quit.png);")
        self.QuitLb.setText("")
        self.QuitLb.setObjectName("QuitLb")
        self.StartLb = QtWidgets.QLabel(self.centralwidget)
        self.StartLb.setGeometry(QtCore.QRect(500, 390, 251, 81))
        self.StartLb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StartLb.setStyleSheet("image: url(:/startBtn/Start.png);")
        self.StartLb.setText("")
        self.StartLb.setObjectName("StartLb")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 80, 471, 201))
        self.label_3.setStyleSheet("image: url(:/Logo/Logo.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 650, 311, 21))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Plesca Virgiliu Copyright © 2021. All rights reserved."))
import BGHD_rc
import Logo_rc
import Start_rc
import mmenu_rc
import quit_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
